name: news_app
description: News App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  auto_route: ^7.8.3
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^5.7.2+3
  flutter_secure_storage: ^9.0.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  kartal: ^3.4.1
  logger: ^1.1.0
  provider: ^6.0.5
  share_plus: ^7.1.0
  shared_preferences: ^2.0.15
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
