name: news_app
description: News App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_inappwebview: <=5.4.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  kartal: ^2.3.1
  logger: ^1.1.0
  provider: ^6.0.3
  share_plus: ^6.2.0
  shared_preferences: ^2.0.15
  vexana: ^3.0.1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
